# Generated by Django 3.1.6 on 2021-02-23 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=100)),
                ('projectLink', models.TextField()),
                ('projectDescription', models.TextField(default='')),
                ('projectIcon', models.ImageField(upload_to='projectIcon')),
                ('coverImage', models.ImageField(upload_to='projectCover')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDevelopment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Screenshots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projectScreenshots')),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SenWeb.project')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderEmail', models.EmailField(max_length=254)),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SenWeb.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='developmentStatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SenWeb.projectdevelopment'),
        ),
        migrations.AddField(
            model_name='project',
            name='projectBusiness',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SenWeb.projectbusiness'),
        ),
        migrations.AddField(
            model_name='project',
            name='projectType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SenWeb.projecttype'),
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('skills', models.TextField()),
                ('selfDescription', models.TextField()),
                ('educationLevel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SenWeb.educationlevel')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SenWeb.position')),
            ],
        ),
    ]
