# Generated by Django 3.1.6 on 2021-02-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SenWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectLink',
            field=models.URLField(max_length=500),
        ),
    ]
