# Generated by Django 3.1.6 on 2021-03-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SenWeb', '0002_auto_20210228_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='fullName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='reviews',
            name='sendNotification',
            field=models.BooleanField(default=False),
        ),
    ]
